'use strict';
const hotel='伊麦酒店 涂家冲 芙蓉中路三段466号';
const src={ikea:'https://www.ikea.cn/cn/zh/stores/changsha/',yuelu:'https://ylsy.hnu.edu.cn/wbly/cgdn/zxdp.htm',park:'https://changsha.voc.com.cn/news/202509/30573142.html?mobile=',xpm:'https://www.x-museum.com/news/detail?materialId=357',xpmNow:'https://you.ctrip.com/sight/changsha148/5073120.html',li:'https://travelnews.qunar.com/ugc/changsha-li-zijian-or-xie-zilong',kaifu:'https://you.ctrip.com/sight/changsha148/9015.html',dufu:'https://www.klook.com/zh-CN/activity/126153-du-fu-jiang-pavilion-ticket/',tea:'https://www.dianping.com/shop/H4eNhErjusDUna1z/photos',teaNorth:'https://m.dianping.com/shop/1370244290',fei:'https://m.dianping.com/shop/k6VEMi9KZTSgdn4c',nanli:'https://pmtmeishi.meituan.com/dp/prefer/list/1846831060',ktv:'https://www.amap.com/place/B0L36LAYKZ',local:'https://linux.do/t/topic/2439746',chui:'https://www.amap.com/place/B0FFJXPGZA'};
const E=(time,end,title,kind,body,place,transit,extra='')=>({time,end,title,kind,body,place,transit,extra});
const days=[
{date:'2026-10-03',short:'10.03',week:'周六',name:'会面与宜家',title:'见面，逛宜家，唱一场 K',weather:'多云 · 16–18°C',intensity:'轻松 / 抵达日',walk:'约 4–6 千步',budget:'¥420–760',route:'黄花机场 → 伊麦酒店 → 洋湖荟聚 / 宜家 → 酒店',note:'航班10:55是落地时间。把机场会面放在11:30–12:00，行李和延误都有余量；午饭后再去宜家。',food:'午饭：酒店附近粉面或清淡家常菜；晚饭：茶港荟聚店，虾饺、肠粉与虾仁饭。',planB:'航班延误超过1小时：缩短宜家到90分钟；KTV改为1小时或取消，不挤掉晚餐和睡眠。',events:[
E('05:47','09:15','吴先到长沙站，先吃早餐休息','单人先到','K1373/K1376 到达长沙站。可以先去酒店寄存行李，提前入住要问前台，未保证。长途火车后找有座位的早餐店休息；需要补觉可自费询问钟点房。','长沙站','长沙站乘2号线至五一广场，换1号线至涂家冲；含步行约35–50分钟。','如去机场接机，建议09:00–09:15从涂家冲出发，1号线至文昌阁换6号线至黄花机场；预留80–100分钟，约10:30到T1。'),
E('11:30','12:00','黄花机场 T1，会面','双人会面','蔡乘 CA4299，08:55 成都天府T2 → 10:55 长沙黄花T1。等到取完行李再约T1到达层明确门号，不把11点作为市区活动的起点。','长沙黄花机场T1航站楼','接机人在T1到达层等待；航班延误时午饭与下午活动顺延。'),
E('12:00','13:30','去酒店寄存行李','交通','两个人带行李，优先机场正规出租车或网约车到酒店。上车前确认目的地是涂家冲的伊麦酒店。','伊麦酒店 涂家冲','打车规划60–90分钟，预算¥100–160/车，仅为估算。省钱备选：6号线文昌阁换1号线涂家冲，含步行约80–100分钟。','入住按酒店实际政策，14:00仅为行程暂定，不代表已确认可入住。'),
E('13:30','14:30','午饭 + 缓一缓','吃饭与休息','先在酒店步行范围内吃一碗不放辣油的肉丝粉，或清淡家常菜。不要为了首餐赶五一广场排队；吃完办入住、换轻装。','涂家冲地铁站','酒店附近步行找店，控制在10分钟内。','两人预算¥50–100；若到酒店较晚，可先机场吃简餐，宜家仍放在午饭之后。'),
E('14:30','15:15','去洋湖荟聚','交通','不用把行李带去商场。乘地铁避开国庆主干道拥堵，若累了两人拼一辆车。','宜家家居长沙商场','涂家冲1号线至侯家塘，换3号线至洋湖湿地，步行到荟聚；门到门约40–55分钟。'),
E('15:15','17:15','一起逛宜家','宜家','先逛样板间和喜欢的家居区，中间坐下来喝水。官网节假日商场10:00–22:00，瑞典餐厅10:00–21:30。','宜家家居长沙商场','长沙市洋湖路253号，荟聚与宜家在同一片商场，步行衔接。','不安排搬运大件；瑞典餐厅可作晚餐备选，具体当日菜单与价格到店确认。'),
E('17:30','19:30','K歌王 · 唱两小时','待订 KTV','选洋湖荟聚店，小包厢两小时足够。高德已核对门店在荟聚L4层；国庆套餐、可用时段和最低消费需要电话确认。','K歌王量贩KTV 洋湖荟聚店','同一商场步行；前往前打0731-89901666确认。','两人包厢预算¥120–240，仅为预算。不要直接买工作日限时券；没房就把KTV改到酒店附近，或直接休息。'),
E('19:30','20:30','茶港：清淡一点的晚饭','微辣友好','茶港·点心·粤菜（长沙荟聚店）：虾饺、叉烧肠粉，再分一份虾仁饭或啫鸡。确认不放辣椒，蘸酱另放。','茶港 点心 粤菜 长沙荟聚店','同商场用餐；排队超过30分钟换宜家瑞典餐厅或南里晓舍。','两人预算¥120–180；评分未在公开页获取，菜品有点评公开图片支持。'),
E('20:30','21:30','回酒店，今天就到这里','休息','买水和次日早餐，洗澡、充电，早点睡。抵达日不再加夜市。','伊麦酒店 涂家冲','3号线洋湖湿地至侯家塘，换1号线涂家冲；约40–55分钟，或打车约25–45分钟，路况估算。')
]},
{date:'2026-10-04',short:'10.04',week:'周日',name:'看展与江景',title:'洋湖看展，晚上去江边',weather:'阵雨或雷雨 · 17–21°C',intensity:'轻松 / 室内为主',walk:'约 5–8 千步',budget:'¥280–600',route:'酒店 → 谢子龙影像艺术馆 → 李自健美术馆 → 酒店午休 → 杜甫江阁',note:'把两座美术馆放在周日，同一片区步行衔接，也能避开周一闭馆争议。10.04有降雨预报，室内看展更合适。',food:'午饭：洋湖附近简餐，或回酒店吃；晚饭：南门口家常湘菜，配一份蒸蛋与汤。',planB:'预约没约到：能进入的公共室外区域拍照，遵从场馆管理；展馆闭馆或雷雨时改荟聚室内休闲，江边夜景移到10.05。',events:[
E('08:30','09:15','早餐，慢慢出门','吃饭','酒店预订截图没有确认早餐权益，先按自费早餐安排。粉面少辣，辣油另放，带折叠伞。','涂家冲地铁站','附近步行。两人预算¥30–50。'),
E('09:15','10:00','到洋湖艺术馆群','交通','两座美术馆彼此很近，今天到达后主要步行。遇明显雷雨时推迟出门。','谢子龙影像艺术馆','酒店打车约25–45分钟，预算¥30–55/车；公共交通可1号线侯家塘换3号线到洋湖湿地后短途打车，约50–70分钟。'),
E('10:00','11:30','谢子龙影像艺术馆','需要核查票务','看一个感兴趣的展就够，建筑和摄影可以一起欣赏。常规10:00–18:00、17:30停止入场；携程公开页列10.01–10.07开放，仍需官方当日确认。','谢子龙影像艺术馆','长沙市潇湘南路一段387号；馆群步行。','网图写“免费”不代表展厅免费。展览收费与预约以“谢子龙影像艺术馆”官方公众号为准；未预约或闭馆不承诺可进入。'),
E('11:40','13:00','李自健美术馆','预约待确认','给主要展区留80分钟，喜欢可以多停留；如果想仔细看，把午饭顺延，不加新景点。','李自健美术馆','从谢子龙步行约5–10分钟。','公开旅客信息列09:30–17:30、需预约，尚未取得2026国庆官方时段。出发前查官方“李自健美术馆”服务号，门票暂按免费常设展核实。'),
E('13:00','14:00','午饭：先坐下来','吃饭','就近点清淡饭菜；馆内咖啡厅可先休息，不保证有完整午餐。周边店满座就回酒店附近吃，不再为餐厅往返远处。','李自健美术馆','馆群附近步行找店，或回酒店打车25–45分钟。两人预算¥80–140。'),
E('14:30','16:30','回酒店午休','留白','今天给两小时午休。晾干雨伞、给手机充电，晚上只逛一个江边片区。','伊麦酒店 涂家冲','从洋湖回酒店；单程规划25–45分钟，雨天加余量。'),
E('17:00','18:00','南门口晚饭 / 小吃','吃饭','想吃湘菜可以提前查费大厨悦方店等商圈门店；怕辣优先蒸蛋、香芋排骨、丝瓜鲍鱼，加小份微辣菜。南门口小吃适合两人分食，别用炸串替代所有正餐。','南门口地铁站','涂家冲乘1号线至南门口；门到门约20–30分钟。','两人预算¥120–180；正餐等位超过30分钟换店。伍娭毑臭豆腐可少辣尝一份，具体摊址与出摊时间当天确认。'),
E('18:20','19:30','杜甫江阁，先看外景','想去 / 夜景','去江阁外的滨江步道看建筑和湘江。光线暗下来后再拍，不强求网图写的固定19:30亮灯时间；亮灯安排未核实。','杜甫江阁','从南门口步行约15–25分钟，或短途打车；大雨与雷电时不走滨江。','外景不用购买登阁票；登阁票价与是否分时预约以官方票务为准，预算¥20–30/人。公开售票页常规09:00–22:00，但当日可能调整。'),
E('20:00','21:00','回去休息','休息','不在江阁附近临时加一大串夜游；天气好可以沿江散步20分钟后回酒店。','伊麦酒店 涂家冲','走回南门口站乘1号线，或在外围正规上车点打车；规划25–40分钟。')
]},
{date:'2026-10-05',short:'10.05',week:'周一',name:'岳麓与城里',title:'书院与山脚，晚上见长沙的热闹',weather:'大部分晴 · 13–25°C',intensity:'中等 / 午休保留',walk:'约 8–12 千步',budget:'¥300–500',route:'酒店 → 岳麓书院 → 爱晚亭 / 岳麓山南门 → 酒店午休 → 五一广场 → 黄兴路 → 解放西',note:'只走岳麓山南门的低强度文化线，不默认登顶。索道运营信息不一致，不把索道作为必需交通。',food:'午饭：湖南大学 / 麓山南路一带清淡粉面；晚饭：费大厨悦方店或炊烟五一店，早一点取号。',planB:'书院没约到：南门山脚和爱晚亭（仍需景区预约）慢走；两处都没约到则改湘江西岸散步，夜游照常。',events:[
E('07:30','08:15','早餐后去岳麓山南门','交通','早一点出门，但不用为了登山五点起床。穿舒服的运动鞋，带学生证原件查询优惠资格。','湖南大学地铁站','涂家冲1号线至侯家塘换4号线至湖南大学；到书院含步行约40–55分钟。'),
E('08:30','10:00','岳麓书院','需单独预约','门匾、讲堂和院落慢慢看，给两个人留一点拍照时间。官网门票常规40元/人；优惠条件在官方预约页核查。','岳麓书院','湖南大学站步行到书院入口约15–20分钟；按实际导引入院。','官网当前写可提前4天（含当天）预约，相当于最早提前3个自然日；10.05建议10.02查票。书院与岳麓山不是同一张预约。'),
E('10:10','11:15','爱晚亭 + 岳麓山山脚','需景区预约','从书院周边走到爱晚亭，在南门片区慢走。保留岳麓山体验，省掉上顶和长队。想登顶就取消当晚部分逛街，不硬加。','岳麓山爱晚亭','书院到爱晚亭步行约10–15分钟；低强度路线约1小时。','索道是否运行未确认；滑道曾有2025停运改造公告，不能照着旧图保证可坐。免费入山仍需在官方公众号预约。'),
E('11:20','12:20','大学城吃午饭','吃饭','就近粉面或家常菜，少辣、辣椒另放；选有座位的店，不在烈日下排网红队。','麓山南路 湖南大学','步行用餐。两人预算¥60–100。','如果上午累了，直接回酒店吃午餐和休息。'),
E('13:00','15:30','回酒店，午休两小时','留白','今天步数最多，下午不塞新景点。夜游可以依据体力把解放西压缩为经过。','伊麦酒店 涂家冲','湖南大学4号线至侯家塘换1号线涂家冲；约40–55分钟。'),
E('16:30','17:45','提早吃晚饭','错峰吃饭','费大厨悦方店可选鲜丝瓜焖鲍鱼、蒸蛋、肉丸汤，炒肉先问能否少辣；炊烟五一店是另一家湘菜备选。','费大厨辣椒炒肉 悦方ID MALL店','涂家冲1号线至黄兴广场或南门口后步行；门到门约25–35分钟。','公开点评历史页费大厨4.4分、约59元/人；不是2026实时评分。两人实际预算¥120–180。等位超过30分钟换附近粤菜/简餐。'),
E('18:00','19:00','五一广场，一起逛一会儿','想去','看看长沙城市中心，可以顺路到IFS周边坐下喝东西；IFS未红标，只作为途经与室内休息点。','五一广场','从悦方沿黄兴路北向步行约15–25分钟；根据人流选外围路径。','国庆按高人流预估，不是实时热度；如地铁站临时限流或跳停，服从现场导引，提前一站步行。'),
E('19:00','20:00','黄兴路步行街 → 解放西','两处都想去','从步行街走到解放西路看看夜景。解放西主要逛街拍照，不默认订酒吧或饮酒。小吃两人分一份即可。','解放西路 长沙','黄兴路步行街到解放西路约10–15分钟；活动总计约1小时。','太平老街与坡子街未红标，只有顺路、体力好才经过，不追加为必到。人挤到走不动就从外围撤出，不穿越围观人群。'),
E('20:15','21:00','回酒店','休息','今晚收在九点左右，明天橘子洲早出门。','伊麦酒店 涂家冲','黄兴广场或南门口乘1号线至涂家冲；约20–35分钟。')
]},
{date:'2026-10-06',short:'10.06',week:'周二',name:'洲头与祈福',title:'清晨橘子洲，午后开福寺',weather:'晴 · 14–27°C',intensity:'中等 / 夜市可跳过',walk:'约 7–10 千步',budget:'¥280–520',route:'酒店 → 橘子洲 → 古开福寺 → 酒店午休 → 杨帆夜市（可选）→ 早睡',note:'橘子洲与岳麓山分开走，减少一天连续暴走。今晚吴要为次日早班高铁做准备，夜市结束后不续摊。',food:'开福寺附近简餐；如想坐着吃清淡粤菜，可选北辰大悦城茶港（短途绕行）。杨帆夜市只尝少量小吃。',planB:'橘子洲没约到：湘江西岸或湘江风光带看洲景；杨帆夜市过于拥挤就取消，回酒店吃饭休息。',events:[
E('07:15','08:15','早餐后去橘子洲','交通','提前确认两人预约码和入园时段，带水、帽子。不要空腹出发。','橘子洲地铁站','涂家冲1号线至五一广场，换2号线至橘子洲；门到门约35–50分钟。'),
E('08:15','10:45','橘子洲：去看青年雕像','想去 / 需预约','岛上距离比照片看起来长。建议预约后再考虑购买观光车，减少往返步行，把时间留给雕像与江景。','橘子洲青年毛泽东雕像','地铁站出站按预约导引入园；观光车起终点按当日安排。','景区入园免费、观光车另收费，双人先预算¥80–100，非核实票价。不坐车全程可能8公里以上，时间与体力预算需增加；排队超过30分钟可缩短游览，不硬走到雕像。'),
E('11:00','12:00','到开福寺片区，先午饭','吃饭','先找有座位的店吃粉面、简餐。素面可以作为轻量加餐，但寺内是否供应、售卖时段和价格未确认。','古开福寺','2号线橘子洲至五一广场，换1号线开福寺；门到门约35–50分钟。','想吃茶港大悦城店需另加往返短途交通，不是开福寺门口餐厅。两人简餐预算¥60–100，粤菜预算¥120–180。'),
E('12:15','13:30','古开福寺，安静一会儿','想去','看寺院建筑、随缘参观。进殿遵守拍摄规则，保持安静，门票与香火安排查官方或现场公告。','古开福寺','开福寺地铁站步行约5–10分钟。','近期旅游平台与旅客页门票通常列10元/人；开放时间不同来源略有差异，放在午间游览以避开开闭门边界，提前核实国庆票务。'),
E('14:00','16:30','回酒店午休 + 整理行李','休息','吴先收好身份证、车票和早餐，确认明早用车；蔡整理后天在成都西下车需要的随身用品。','伊麦酒店 涂家冲','开福寺站1号线直达涂家冲；门到门约30–45分钟。','今日最重要的提醒：确认次日05:45酒店出发的车辆及叫车备选，目标06:25–06:40到长沙南站。'),
E('17:00','17:50','去杨帆夜市（可选）','交通 / 看体力','如果午休后仍有精神，提早去吃一轮。累了就直接在酒店附近吃晚饭，这个晚上随时可以取消。','杨帆夜市 长沙','涂家冲1号线至五一广场，换2号线至万家丽广场后步行；规划45–60分钟，按高德实时导引选择出口。'),
E('17:50','18:50','杨帆夜市，少量分食','想去 / 可跳过','挑2–3样：糖油粑粑、清淡烤串、熟制蒜蓉海鲜。不点口味虾作唯一晚饭；先问价与份量，再点不辣或辣酱另放。','杨帆夜市 长沙','夜市内步行；不是每个摊位都有稳定评分，不贴高分标签。','两人预算¥60–120，拥挤或找不到座位就撤。小龙虾不保证在10月新鲜在售，不强行打卡。'),
E('19:00','20:00','回酒店，今晚提早收尾','早睡','明早要起得早，20:00前回酒店，洗澡后21:00–21:30准备睡觉。不再去酒吧或另一个夜市。','伊麦酒店 涂家冲','2号线万家丽广场至五一广场换1号线涂家冲；约45–60分钟。')
]},
{date:'2026-10-07',short:'10.07',week:'周三',name:'分别返程',title:'好好告别，各自平安到家',weather:'下午零星降雨 · 14–28°C',intensity:'返程 / 以赶车为主',walk:'约 2–4 千步',budget:'¥160–300',route:'吴：酒店 → 长沙南；蔡：酒店 → 长沙站 → 成都西',note:'吴清晨先走，蔡下午再走。今天没有“双人一整天”的活动；长沙南站与长沙站不能混淆。',food:'吴自带早餐和水；蔡睡醒吃早餐，午饭选酒店附近坐得舒服的店，并带晚饭上K字头列车。',planB:'早班预约车迟迟未接：05:35开始调用备选正规车，目标06:40前到站。若确有晚点或赶不上，直接用12306/车站服务处理，不赌晚几分钟还能进站。',events:[
E('05:00','05:40','吴起床，身份证和早餐随身','吴 · 返程','检查车次、车站、检票口。G1778最终付款列表显示已支付；早前截图为无座，但已支付列表没显示席别，最新席别以12306订单为准。','伊麦酒店 涂家冲','取已备好的早餐，不依赖此时营业的早餐店。','蔡可以继续休息；如陪送，往返另加时间，不默认两个人都必须五点起床。'),
E('05:45','06:40','吴打车去长沙南站','吴 · 赶车','建议最晚05:45从酒店出发，06:25–06:40到站，给安检和找检票口留44–59分钟。早上不押注首班地铁。','长沙南站','规划35–55分钟，预算¥40–70/车，实际以实时路况为准；前晚预约并保留备选。'),
E('07:24','14:06','吴：G1778 → 上海虹桥','已支付截图','2026.10.07 07:24 长沙南 → 14:06 上海虹桥。二等座/无座及车厢请核对最新订单，不把旧付款页当最终席位证明。','长沙南站','以12306当日检票通知为准，建议06:40前进站。','车次时刻来自上传截图，非实时铁路核验。'),
E('09:00','11:30','蔡早餐，酒店附近慢慢收尾','蔡 · 单人','睡醒再吃，整理行李、给充电器和洗漱用品拍个检查照。今天不安排跨江或远距离景点。','伊麦酒店 涂家冲','附近步行。'),
E('12:00','13:00','蔡退房、寄存行李、午饭','蔡 · 退房','退房时间暂按12:00计划，必须按实际订单与前台确认。需要寄存行李提前问前台，寄存服务不保证；如果不能寄存就带上行李就近用餐。','伊麦酒店 涂家冲','步行到附近饭店。','截图是酒店预订页面，未展示最终订单权益；早餐、房型、两人登记与退房时刻需自行核对。'),
E('14:30','15:30','蔡取行李，去长沙站','蔡 · 赶车','14:30左右离开酒店，目标15:30前到长沙站；一旦交通有异常立即提前动身，不在出发前才买伴手礼。','长沙站','涂家冲1号线至五一广场，换2号线长沙火车站；含步行安检外交通约35–50分钟。打车约25–45分钟，均为规划估算。','注意是市区长沙站，不是长沙南站。带水、纸巾、充电宝与晚饭；硬卧/硬座/无座未在附件展示，按最终订单核查。'),
E('16:35','23:59','蔡：K502/K503 → 成都西','车次待核最终订单','10.07 16:35 长沙站出发，截图列10.08 10:52抵达成都西，历时18小时17分。10.07晚是在车上，不是住酒店。','长沙站','15:30前进站，找好检票口；车票最终席位、开行状态以12306订单为准。','到达提醒会在日历中另外创建于10.08 10:52。上传的是车次信息页，未展示付款状态；按用户已预订说明录入。')
]}
];
const food=[
{name:'茶港 · 点心 · 粤菜',branch:'长沙荟聚店',area:'洋湖',day:'10.03 晚餐首选',cost:'双人 ¥120–180',rating:'公开菜品可核查 · 未获取实时评分',order:'虾饺 + 叉烧肠粉 + 虾仁饭，或分享一份啫鸡。',reason:'宜家、KTV与晚饭在同一商场；对微辣偏好友好。具体菜式口味要现场确认。',evidence:'点评公开图片页能看到虾饺、肠粉等菜品与网友上传记录；未读取完整评价正文。',url:src.tea,map:'茶港 点心 粤菜 长沙荟聚店'},
{name:'南里晓舍 · 新淮扬菜',branch:'荟聚店',area:'洋湖',day:'10.03 晚餐备选',cost:'双人 ¥120–200',rating:'美团店页存在 · 评分未公开读取',order:'到店看菜单选清蒸鱼、清淡汤菜等；菜品是否在售需确认。',reason:'茶港长队时就近替换。淮扬菜作为清淡选择是菜系判断，不是已验证的菜单。',evidence:'美团公开优惠页显示该门店和2026年活动有效期；活动不代表实时评分或一定能用券。',url:src.nanli,map:'南里晓舍 新淮扬菜 荟聚店'},
{name:'宜家瑞典风味餐厅',branch:'长沙宜家',area:'洋湖',day:'10.03 随时补给 / 备选',cost:'双人 ¥80–140',rating:'官网核实营业时间 · 无评分排序',order:'到店选不辣主食或肉丸，具体菜单和价格现场核对。',reason:'逛累了不用离开宜家，有座位比追高分更适合抵达日。',evidence:'官网节假日餐厅10:00–21:30，商场10:00–22:00；特殊安排以商场公告为准。',url:src.ikea,map:'宜家瑞典风味餐厅 长沙'},
{name:'费大厨辣椒炒肉',branch:'悦方 ID MALL 店',area:'五一 / 南门口',day:'10.05 16:30 提早吃',cost:'双人 ¥120–180',rating:'大众点评历史页 4.4 · 约 ¥59/人',order:'少辣炒肉先确认；蒸蛋、香芋蒸排骨、丝瓜鲍鱼或肉丸汤。',reason:'菜品里有清淡搭配，距离夜游片区近。招牌菜含辣椒，不能承诺完全不辣。',evidence:'评分与人均来自1年多前抓取的公开门店页，只作历史参考；页面片区标签与门店地址信息有冲突，定位以店名和高德复核。',url:src.fei,map:'费大厨辣椒炒肉 悦方ID MALL店'},
{name:'炊烟小炒黄牛肉',branch:'五一广场店',area:'五一 / 南门口',day:'10.05 湘菜备选',cost:'双人 ¥140–200',rating:'高德显示5分 · 仅见2016年旧评',order:'先问黄牛肉能否少辣，再加不辣蔬菜、蒸蛋或汤；菜单到店确认。',reason:'位置在东牌楼街58号，能衔接五一商圈。高德旧评分样本很少，不能用来证明今日高口碑。',evidence:'已核对高德门店定位；公开评价来自2016.10，时效不足，所以只作位置与备选参考。',url:src.chui,map:'炊烟小炒黄牛肉 五一广场店'},
{name:'茶港 · 点心 · 啫啫煲',branch:'长沙大悦城店',area:'开福 / 北辰',day:'10.06 清淡正餐备选',cost:'双人 ¥120–180',rating:'大众点评历史页 4.5 · 约 ¥61/人',order:'水晶虾饺、菠萝包、叉烧肠粉，或蟹肉滑蛋虾仁类主食。',reason:'适合想坐着吃清淡餐的一天，但从开福寺需额外短途交通；不是寺门口餐厅。',evidence:'评分和网友推荐菜可从点评历史页读取，抓取约1年多前。当前分数、菜单与营业情况需在App确认。',url:src.teaNorth,map:'茶港 点心 啫啫煲 长沙大悦城店'},
{name:'伍娭毑臭豆腐 / 黑色经典',branch:'南门口 / 就近门店',area:'五一 / 南门口',day:'10.04 或 10.05 分食一份',cost:'两人尝鲜 ¥10–25',rating:'2026年网友亲历 · 偏好有分歧',order:'一份两人分，辣椒另放；少量尝鲜，不连吃多份炸物。',reason:'本地自述网友推荐伍娭毑，另一位更偏好黑色经典；不把任何一家写成人人认同的“最好”。',evidence:'2026.06论坛分享含作者多次品尝自述与游客反馈；身份未经独立验证。摊位地址、时间和门店存在要出发前复核。',url:src.local,map:'伍娭毑臭豆腐 长沙 南门口'},
{name:'糖油粑粑 / 米粉 / 乔伯凉面',branch:'顺路选择，不为小吃远行',area:'五一 / 南门口',day:'早餐与小份加餐',cost:'每人 ¥10–25 / 项',rating:'米粉为类型建议 · 凉面有亲历来源',order:'米粉辣油另放；糖油粑粑两人分食；乔伯凉面点前确认辣度。',reason:'以能坐下、价格标清楚、出餐快为优先。旅客常见的臭豆腐与本地自述的凉面可各尝一次。',evidence:'乔伯凉面来自2026.06亲历论坛；其他为食品类型建议，不代表已核查具体摊位评分。',url:src.local,map:'乔伯凉面 长沙 白沙路'}
];
const reservations=[
{id:'park',name:'岳麓山 + 橘子洲',when:'10.05 岳麓山；10.06 橘子洲',deadline:'10.02查岳麓山；10.03查橘子洲',channel:'微信搜索“岳麓山 橘子洲旅游区”，按当日可约日期选择两人的分时名额。',body:'2025国庆官方渠道报道写提前3天、分时入园，2026具体放号时间未核实。不要把预约成功当作能任意时段入园，先以当前官方页面为准。橘子洲观光车另买，不能替代入园预约。',fallback:'没约到就走湘江两岸，不在入口赌现场放行。',url:src.park},
{id:'academy',name:'岳麓书院：单独约票',when:'10.05 08:30–10:00',deadline:'10.02开始查可约日期',channel:'微信搜索“岳麓书院”，与山门预约分别办理。',body:'湖南大学官网当前写提前4天（含当天），未预约谢绝入院，常规票40元/人。即包含当天在内的4天，不是提前4个自然日。学生票以平台审核条件和本人学生证为准。',fallback:'没约到保留已预约的岳麓山南门、爱晚亭慢走。',url:src.yuelu},
{id:'xpm',name:'谢子龙影像艺术馆',when:'10.04 10:00–11:30',deadline:'10.01–10.03查当期展览与票务',channel:'微信搜索“谢子龙影像艺术馆”，核实2026国庆开放公告与展览票。',body:'常规开放10:00–18:00、17:30停止入场。携程公开页列国庆10.01–10.07开放，年份与特殊公告仍应官方确认；旧官方公告仅作常规参考。不把网图“免费”当作全部展厅免费。',fallback:'没有票时仅在允许进入的公共室外区域看看，或改室内商场。',url:src.xpmNow},
{id:'li',name:'李自健美术馆',when:'10.04 11:40–13:00',deadline:'10.01–10.03查官方可约名额',channel:'微信搜索“李自健美术馆”服务号，查票务中心。',body:'近期旅客公开信息称常设展免费、需预约、09:30–17:30。尚未取得2026国庆官方公告，时段与展览以公众号当天信息为准；上午不押注能直接进馆。',fallback:'未约到时仅在管理允许的公共外部区域停留；雨大改荟聚。',url:src.li},
{id:'ktv',name:'K歌王量贩KTV · 洋湖荟聚店',when:'10.03 17:30–19:30',deadline:'10.01–10.02电话确认小包厢',channel:'荟聚L4层；电话0731-89901666。',body:'高德门店位置已核对。电话确认国庆可用时段、2小时小包、总价、是否需另付服务费以及团购券适用日期。门店有位置不等于有房，尚未替你预订。',fallback:'无合适包厢就换酒店附近KTV，或缩短/取消，不拖到深夜。',url:src.ktv},
{id:'car',name:'10.07 早班高铁用车',when:'05:45酒店出发，06:25–06:40到长沙南',deadline:'10.06 20:00前落实',channel:'正规网约车预约或酒店前台协助叫车，保留第二种叫车方式。',body:'吴07:24出发，早上不依赖首班地铁。提前核对上车地点、车牌与长沙南站，预算¥40–70/车。预约不代表绝对有车，司机未确认就准备备选。',fallback:'05:35若无法确认车辆，启动备选正规车并提前出发。',url:'https://www.12306.cn'},
{id:'hotel',name:'酒店订单与两人入住登记',when:'10.03入住；10.07退房',deadline:'出发前核查订单',channel:'以你实际已订的酒店订单或前台答复为准。',body:'酒店截图为房型预订页面，显示选择1间1人，但房型允许2人。你已告知预订完成；需核对两人实名入住、实际房型、早餐、寄存与退房时刻，截图的313元不是确认订单总价。',fallback:'吴10.03清晨可先问寄存或钟点房，提前入住不保证。',url:'https://m.ctrip.com/html5/hotel/hoteldetail/125069349.html'}
];
let state={view:'itinerary',day:0,area:'全部'};let local={};try{local=JSON.parse(localStorage.getItem('changsha-two-v1')||'{}')}catch{};
const save=()=>{try{localStorage.setItem('changsha-two-v1',JSON.stringify(local))}catch{toast('浏览器未允许保存，本次操作仍可使用')}};
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const map=q=>'https://uri.amap.com/search?keyword='+encodeURIComponent(q)+'&city='+encodeURIComponent('长沙')+'&view=map&src=changsha-for-two';
const mapLink=q=>`<a href="${map(q)}" target="_blank" rel="noopener">高德导航</a>`;
const sourceLink=(url,label='核查来源')=>`<a href="${url}" target="_blank" rel="noopener">${label}</a>`;
function toast(m){let t=document.getElementById('toast');t.textContent=m;t.style.display='block';clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.style.display='none',4000)}
function changeView(v){state.view=v;document.querySelectorAll('[data-view]').forEach(b=>{b.classList.toggle('active',b.dataset.view===v);b.setAttribute('aria-current',b.dataset.view===v?'page':'false')});render();window.scrollTo({top:0,behavior:'auto'})}
function render(){document.getElementById('view').innerHTML=({itinerary:renderDay,food:renderFood,booking:renderBooking,tickets:renderTickets,guide:renderGuide}[state.view])()}
function renderDay(){const d=days[state.day];return `<div class="days" role="tablist" aria-label="选择日期">${days.map((x,i)=>`<button class="day-button ${i===state.day?'active':''}" data-day="${i}" role="tab" aria-selected="${i===state.day}"><small>DAY ${i+1} · ${x.week}</small><strong>${x.short}</strong><span>${x.name}</span></button>`).join('')}</div><div class="day-head"><div><h2>${d.title}</h2><span class="pill">${d.intensity}</span><span class="pill gray">${d.weather}</span></div><button class="small" data-calday>这一天加入日历</button></div><div class="daily-layout"><div class="timeline">${d.events.map((e,i)=>{const k=`event-${state.day}-${i}`;return `<article class="event ${local[k]?'done':''}"><div class="event-time">${e.time.slice(0,2)}<br>${e.time.slice(3)}</div><div class="event-top"><span class="pill ${e.kind.includes('吃')?'yellow':''}">${e.kind}</span><label class="check-done"><input type="checkbox" data-done="${k}" ${local[k]?'checked':''}>完成</label></div><h3>${e.title}</h3><p>${e.body}</p><details><summary>交通、费用与贴心细节 · 至 ${e.end}</summary><p>${e.transit}</p>${e.extra?`<p>${e.extra}</p>`:''}</details><div class="actions">${mapLink(e.place)}<button data-event-cal="${i}">日历提醒</button></div></article>`}).join('')}</div><aside class="day-aside"><div class="day-note"><span class="eyebrow purple">TODAY'S RHYTHM</span><h3>今天不赶路</h3><p>${d.note}</p><div class="stat-row"><div class="stat">步数估算<strong>${d.walk}</strong></div><div class="stat">${state.day===4?'分别返程合计':'双人当天预算'}<strong>${d.budget}</strong></div></div><p class="meta">不含已订机票车票与酒店；餐饮、交通和门票均为估算。</p></div><div class="note-card"><h3>今天的路线</h3><p>${d.route}</p><h3 style="margin-top:16px">好好吃饭</h3><p>${d.food}</p><button class="small" data-jump="food">看餐厅备选</button></div><div class="note-card"><h3>如果天气或人流不配合</h3><p>${d.planB}</p><p>预计交通已留国庆余量，实际拥堵、地铁限流与预约名额以现场和官方为准。</p></div></aside></div>`}
function renderFood(){return `<div class="view-heading"><h2>湘味要尝，微辣要说清楚</h2><p>按路线选店，超过30分钟就换。这里的分数是可读取的历史记录；未取得实时分数的餐厅明确标注，不伪装成最新高分榜。</p></div><div class="callout"><strong>点单可以直接说</strong><p>“我们只能吃一点点辣，请少放辣椒，不放额外辣油，辣椒和蘸酱单独放。哪些菜可以做完全不辣？”</p><p class="meta">两人每餐：1份想尝的湘菜 + 1份不辣菜 + 1份汤或蒸蛋。海鲜可以吃，优先熟制清蒸 / 蒜蓉，不把口味虾当作微辣保底。</p></div><div class="section-bar">${['全部','洋湖','五一 / 南门口','开福 / 北辰'].map(a=>`<button class="filter ${state.area===a?'active':''}" data-area="${a}">${a}</button>`).join('')}</div><div class="grid">${food.filter(f=>state.area==='全部'||f.area===state.area).map(f=>`<article class="food-card"><span class="eyebrow">${f.day}</span><h3>${f.name}<br><span class="meta">${f.branch}</span></h3><div class="rating">${f.rating}</div><div class="meal">${f.order}</div><span class="pill yellow">${f.cost}</span><p>${f.reason}</p><details><summary>推荐依据与时效</summary><p>${f.evidence}</p></details><div class="actions">${mapLink(f.map)}${sourceLink(f.url,'看公开来源')}</div></article>`).join('')}</div><div class="callout"><strong>平台核查的实际范围</strong><p>高德：门店定位和部分旧评价可读取。大众点评：部分门店历史评分、推荐菜和图片可读取。美团：南里晓舍公开活动页可读取，评分与KTV套餐未读取。小红书：公开入口跳转登录页，未读取站内笔记或博主评价。</p><p class="meta">若希望按最新“4.7分以上 + 近30天评价”再筛一轮，可在对应App确认；不必为了分数额外绕路。本地自述亲历与旅客感受均为个人偏好，非身份背书。</p></div>`}
function renderBooking(){let n=reservations.filter(r=>local['book-'+r.id]).length;return `<div class="view-heading"><h2>出发前，把这几件事落实</h2><p>已确认 ${n} / ${reservations.length} 项 · 勾选只记录在当前设备，不代表平台已完成预约。</p><button class="primary" data-open-calendar>导出出行与预约准备提醒</button></div>${reservations.map(r=>`<article class="reserve-card ${local['book-'+r.id]?'confirmed':''}"><div class="reservation-head"><div><span class="pill yellow">${r.deadline}</span><h3 style="margin-top:9px">${r.name}</h3><div class="meta">${r.when}</div></div><label><input type="checkbox" data-book="${r.id}" ${local['book-'+r.id]?'checked':''}>已落实</label></div><p><strong>怎么确认：</strong>${r.channel}</p><p>${r.body}</p><details><summary>预约不到时的替代安排</summary><p>${r.fallback}</p></details><label>记下已预约时段或确认信息（仅此设备）<input type="text" maxlength="200" data-book-note="${r.id}" placeholder="例如：10.05 08:30，已约两人" value="${esc(local['note-'+r.id]||'')}"></label><div class="actions">${sourceLink(r.url)}</div></article>`).join('')}<div class="callout"><strong>提醒怎样生效</strong><p>页面只是显示日程，不会在关闭后自动弹通知。用上方按钮下载并导入 .ics 日历，检查手机日历通知权限；导入文件不会替你完成预约、订车或购票。</p></div>`}
function ticket(t){return `<article class="ticket-card"><span class="pill ${t.status==='已支付截图'?'yellow':''}">${t.status}</span><span class="pill gray">${t.person}</span><h3 style="margin-top:12px">${t.code} · ${t.date}</h3><div class="route-flight"><div><strong>${t.start}</strong><span>${t.from}</span></div><span class="route-symbol">—</span><div><strong>${t.end}</strong><span>${t.to}</span></div></div><p>${t.note}</p><div class="actions">${mapLink(t.map)}<button data-open-calendar>导出提醒</button></div></article>`}
function renderTickets(){return `<div class="view-heading"><h2>票、酒店，和安心的缓冲</h2><p>交通时间来自上传截图，未查询订单或实时运行状态。姓名仅用旅伴称呼，页面不放身份证、手机号、订单号或票号。</p></div><div class="grid">${ticket({status:'已出票截图',person:'蔡 · 成都出发',code:'CA4299',date:'10.03 周六',start:'08:55',end:'10:55',from:'成都天府 T2',to:'长沙黄花 T1',map:'成都天府国际机场T2',note:'建议06:45–07:00到天府T2；具体值机截止按航司通知，航班截图注明无餐食。落地后约11:30–12:00在T1到达层会面。'})}${ticket({status:'已支付截图',person:'吴 · 上海出发',code:'K1373/K1376',date:'10.02 → 10.03',start:'16:34',end:'05:47 +1',from:'上海松江',to:'长沙站',map:'上海松江站',note:'10.02建议15:30前到上海松江站。检票口11A11B北区来自旧截图，可能变化，以当天站内屏幕与12306为准；早到后先休息。'})}${ticket({status:'已支付截图',person:'吴 · 返回上海',code:'G1778',date:'10.07 周三',start:'07:24',end:'14:06',from:'长沙南站',to:'上海虹桥',map:'长沙南站',note:'05:00起床、05:45酒店出发、06:25–06:40到站。早前未付款截图为无座，最新已支付列表未显示席别，需要核对最终订单。'})}${ticket({status:'按用户已订说明录入',person:'蔡 · 返回成都',code:'K502/K503',date:'10.07 → 10.08',start:'16:35',end:'10:52 +1',from:'长沙站',to:'成都西',map:'长沙站',note:'10.07 14:30酒店出发、15:30前到市区长沙站。上传为车次信息页，付款与席位未展示；约18小时17分，带晚饭与早餐。'})}<article class="ticket-card full"><span class="pill yellow">用户已预订 · 最终权益待核</span><h3 style="margin-top:12px">伊麦酒店（五一广场涂家冲地铁站店）</h3><p>天心区芙蓉中路三段466号 · 地铁1号线涂家冲站，截图称步行250米 / 4分钟。</p><div class="stat-row"><div class="stat">入住日期<strong>10.03 周六</strong></div><div class="stat">退房日期<strong>10.07 周三</strong></div><div class="stat">住宿<strong>4 晚 · 1 间</strong></div></div><p>你提供的是酒店房型预订页，不是最终订单页。房型、早餐、订单金额、入住退房时刻以实际订单为准；暂按14:00入住、12:00退房排计划。截图选择“1人”，入住时确认两人实名登记。</p><p>吴10.03 05:47已到，但酒店不保证清晨可入住。可先问寄存、提前入住或自费钟点房。10.07吴先走，蔡中午退房后如需寄存先问前台。</p><div class="actions">${mapLink(hotel)}${sourceLink('https://m.ctrip.com/html5/hotel/hoteldetail/125069349.html','核对酒店地址')}<button data-open-calendar>导出入住退房提醒</button></div></article></div>`}
function renderGuide(){return `<div class="view-heading"><h2>少一点折腾，多一点舒服</h2><p>路线以涂家冲酒店为中心。国庆人流是规划预估，不是实时监测；天气查询于10.01，临出发再复核。</p></div><div class="grid"><article class="guide-card"><h3>交通怎么选</h3><ul><li>机场进城带行李：两人合乘正规车更轻松。</li><li>五一、黄兴、解放西：优先地铁 + 步行，避开商圈打车排队。</li><li>洋湖艺术馆群：短途打车换舒适；两个馆之间步行。</li><li>10.07吴早班车：前晚预约用车并准备备选，不依赖首班地铁。</li><li>临时地铁跳停 / 景区限流：听现场安排，外围站点出入，不挤最后一班车。</li></ul></article><article class="guide-card"><h3>天气和雨天替换</h3><p>10.03多云16–18°C；10.04可能阵雨或雷雨17–21°C；10.05大部分晴13–25°C；10.06晴14–27°C；10.07下午零星降雨14–28°C。</p><p>薄外套、折叠伞、舒适鞋。10.04优先室内看展；雷雨时取消滨江步道，夜景顺延到10.05。没有把烟花列为必看，因为未取得2026国庆官方场次。</p><p class="meta">预报会变化，尤其降雨时段；离开酒店前看天气App和官方公告。</p></article><article class="guide-card"><h3>两个人的预算</h3><p>5天额外开销粗估 <strong>¥1,440–2,680</strong>，包括餐饮、市内交通、KTV和基础门票；不含机票车票、酒店、大额购物。</p><p>其中艺术展票暂预留较宽区间，没取得实时票价。每天预算是上限参考，不需要为了“花够”增加消费。</p><p>餐厅11:00或16:30–17:00开始更容易避开正餐高峰。排队30分钟是换店阈值，艺术馆/观光车也保留随时退出的选择。</p></article><article class="guide-card"><h3>随身带好</h3><ul><li>实体身份证、符合优惠资格的学生证。</li><li>预约码截图、酒店订单、最终席位信息。</li><li>充电宝、线、水、纸巾、薄外套和伞。</li><li>长途列车的饭、水与保暖衣物。</li><li>确认酒店地址是涂家冲，不因店名含“五一广场”就导航到五一广场。</li></ul></article></div><div class="section-bar"><h3>你的红色标记，全都考虑进去了</h3></div><div class="table-wrap"><table><thead><tr><th>想去的地方</th><th>安排</th><th>舒适调整</th></tr></thead><tbody><tr><td>宜家、唱K</td><td>10.03下午与傍晚</td><td>同在荟聚，抵达日不再加夜市</td></tr><tr><td>谢子龙、李自健</td><td>10.04上午</td><td>同片区；周日看展避开周一争议</td></tr><tr><td>杜甫江阁</td><td>10.04晚上</td><td>优先看外景，雷雨则顺延</td></tr><tr><td>岳麓山、岳麓书院</td><td>10.05上午</td><td>山脚文化线，不默认登顶或坐索道</td></tr><tr><td>五一广场、黄兴路、解放西</td><td>10.05晚上</td><td>同片区一条线，九点左右回酒店</td></tr><tr><td>橘子洲、古开福寺</td><td>10.06上午与午间</td><td>洲内优先观光车；下午午休</td></tr><tr><td>杨帆夜市</td><td>10.06傍晚，可跳过</td><td>一小时分食，20:00回酒店</td></tr><tr><td>湖南博物馆</td><td>不安排</td><td>按你的要求排除</td></tr></tbody></table></div><details style="margin:20px 0"><summary>看你上传的景点标记原图</summary><div class="reference-images"><a href="places-night.jpg" target="_blank" rel="noopener"><img src="places-night.jpg" alt="用户上传的长沙景点清单，红色标记五一广场、橘子洲、岳麓山等想去的景点">山水与夜游原图</a><a href="places-art.jpg" target="_blank" rel="noopener"><img src="places-art.jpg" alt="用户上传的长沙艺术馆清单，红色标记谢子龙与李自健美术馆">艺术馆原图</a></div></details><details><summary>资料来源与核查记录</summary>${[
['宜家官网',src.ikea,'商场地址、节假日营业与餐厅时间；核查10.01。'],['湖南大学岳麓书院官网',src.yuelu,'预约提前4天（含当天）、时段和常规票价；不把旧旅游笔记当最新规则。'],['岳麓山 / 橘子洲2025国庆预约报道',src.park,'用于预约提前量参考；2026分时与放号需官方公众号复核。'],['谢子龙官方旧公告',src.xpm,'只作为常规开放参考；2026国庆公告未完整核实。'],['谢子龙携程景点页',src.xpmNow,'公开页列国庆特殊开放时段，出发前向官方确认适用年份。'],['李自健近期旅客公开信息',src.li,'预约、免费常设展与时间为旅客资料，尚无2026官方交叉确认。'],['高德 · K歌王荟聚店',src.ktv,'门店位置与电话；不保证有包厢或国庆团购可用。'],['大众点评 · 茶港荟聚店',src.tea,'推荐菜图片与上传记录；未取得实时评分或完整评价。'],['美团 · 南里晓舍荟聚店',src.nanli,'公开活动页，非完整评分/菜单信息。'],['大众点评 · 费大厨悦方店',src.fei,'历史公开页4.4分、人均约59元；抓取1年多前，定位标签有冲突，需地图复核。'],['大众点评 · 茶港大悦城店',src.teaNorth,'历史公开页4.5分、人均约61元；不代表当前分数。'],['高德 · 炊烟五一店',src.chui,'定位可用，5分仅见2016旧评，不用作实时高分证据。'],['2026年网友亲历美食讨论',src.local,'地方用户自述、实吃图片与游客偏好讨论，身份未独立验证；不照搬其强辣选择。'],['古开福寺携程景点页',src.kaifu,'票价与中午可游时段参考，仍按官方现场公告。'],['杜甫江阁公开售票页',src.dufu,'常规开放时间参考；2026国庆票价、亮灯和烟花未核实。'],['小红书公开入口','https://www.xiaohongshu.com/explore','10.01访问跳转登录页，未读取笔记，未虚构小红书网友推荐。']].map(s=>`<div class="source-card">${sourceLink(s[1],s[0])}<p>${s[2]}</p></div>`).join('')}</details>`}
const essential=[
{date:'2026-10-02',time:'15:30',end:'16:00',title:'吴：到上海松江站，准备乘K1373/K1376',place:'上海松江站',body:'16:34发车。建议15:30到站；检票口以当日12306和站内屏幕为准。',person:'wu',alarm:90},
{date:'2026-10-02',time:'16:34',end:'16:54',title:'吴：K1373/K1376出发 → 长沙站',place:'上海松江站',body:'10.03 05:47抵达长沙站，车次信息来自上传截图；最终席别按订单核查。',person:'wu',alarm:60},
{date:'2026-10-03',time:'05:47',end:'06:07',title:'吴：长沙站下车，先休息',place:'长沙站',body:'先问酒店寄存/钟点房，提前入住不保证；不要混淆长沙南。',person:'wu',alarm:30},
{date:'2026-10-03',time:'06:45',end:'07:00',title:'蔡：到成都天府T2办理登机',place:'成都天府机场T2',body:'CA4299 08:55起飞，建议06:45–07:00到机场。航司截止时间以当日通知为准。',person:'cai',alarm:90},
{date:'2026-10-03',time:'08:55',end:'10:55',title:'蔡：CA4299 成都天府T2 → 长沙黄花T1',place:'成都天府T2 / 长沙黄花T1',body:'已出票截图。无餐食。11:30–12:00机场会面，落地后取行李。',person:'cai',alarm:1440},
{date:'2026-10-03',time:'09:00',end:'09:15',title:'吴：出发去黄花机场T1接机',place:'涂家冲 → 黄花机场T1',body:'地铁1号线文昌阁换6号线黄花机场，预留80–100分钟，目标10:30到机场。',person:'wu',alarm:30},
{date:'2026-10-03',time:'11:30',end:'12:00',title:'计划：黄花机场T1会面',place:'长沙黄花机场T1到达层',body:'航班10:55落地；会面时间等取行李后确认，延误顺延。',person:'both',alarm:30},
{date:'2026-10-03',time:'14:00',end:'14:30',title:'暂定：伊麦酒店入住 / 寄存',place:hotel,body:'10.03–10.07四晚，用户已预订；14:00为安排假设，入住时刻、早餐、房型与两人登记按实际订单确认。',person:'both',alarm:60},
{date:'2026-10-01',time:'21:00',end:'21:20',title:'准备：核对美术馆预约、酒店订单与KTV时段',place:'官方公众号 / 酒店 / K歌王',body:'查10.04谢子龙与李自健的官方票务；电话0731-89901666确认10.03 17:30小包两小时。未代订。',person:'both',alarm:10},
{date:'2026-10-02',time:'09:00',end:'09:20',title:'准备：查10.05岳麓山与书院可约名额',place:'微信官方公众号',body:'书院与山门分别预约。09:00是自选检查时间，不是核实的放号时间；当前可约日期以公众号为准。',person:'both',alarm:10},
{date:'2026-10-03',time:'08:00',end:'08:20',title:'准备：查10.06橘子洲两人名额',place:'岳麓山 橘子洲旅游区公众号',body:'按官方当前分时页面预约。08:00为自选查看时间，不是确认放号时间；观光车另买。',person:'both',alarm:10},
{date:'2026-10-06',time:'20:00',end:'20:20',title:'准备：落实明早05:45去长沙南的车辆',place:hotel,body:'预约正规车，确认司机与酒店上车点，并准备第二种叫车方式；不依赖首班地铁。',person:'wu',alarm:30},
{date:'2026-10-07',time:'05:00',end:'05:20',title:'吴：起床，早餐身份证随身',place:hotel,body:'07:24 G1778长沙南出发；05:45离开酒店，06:25–06:40到站。',person:'wu',alarm:10},
{date:'2026-10-07',time:'05:45',end:'06:40',title:'吴：酒店出发去长沙南站',place:'伊麦酒店 → 长沙南站',body:'预约车并准备备选，最晚目标06:40到站。费用和交通为估算。',person:'wu',alarm:30},
{date:'2026-10-07',time:'07:24',end:'14:06',title:'吴：G1778 长沙南 → 上海虹桥',place:'长沙南站',body:'已支付截图；早前页面为无座，最终席位请查最新12306订单。',person:'wu',alarm:60},
{date:'2026-10-07',time:'12:00',end:'12:30',title:'暂定：蔡办理伊麦酒店退房',place:hotel,body:'12:00为计划假设，按订单/前台确认；行李寄存先问前台，14:30出发去长沙站。',person:'cai',alarm:60},
{date:'2026-10-07',time:'14:30',end:'15:30',title:'蔡：取行李去长沙站（非长沙南）',place:'伊麦酒店 → 长沙站',body:'1号线五一广场换2号线长沙火车站，或打车；目标15:30前到站，16:35出发。',person:'cai',alarm:30},
{date:'2026-10-07',time:'16:35',end:'17:00',title:'蔡：K502/K503 长沙站 → 成都西',place:'长沙站',body:'10.08 10:52到成都西。用户称已预订，截图为车次页，最终订单状态和席位请核查。',person:'cai',alarm:60},
{date:'2026-10-08',time:'10:52',end:'11:12',title:'蔡：到成都西，检查行李后下车',place:'成都西站',body:'计划抵达时间来自上传截图；实际时刻按列车运行情况。',person:'cai',alarm:30}
];
function eventPerson(day,index){if(day===0&&index===0)return 'wu';if(day===4)return index<=2?'wu':'cai';return 'both'}
function utcStamp(date,time){return new Date(`${date}T${time}:00+08:00`).toISOString().replace(/[-:]/g,'').replace('.000','')}
function icsEscape(s){return String(s).replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/;/g,'\\;').replace(/,/g,'\\,')}
function fold(line){let parts=[],part='',size=0;for(const c of line){const bytes=new TextEncoder().encode(c).length;if(size+bytes>73){parts.push(part);part=' '+c;size=1+bytes}else{part+=c;size+=bytes}}parts.push(part);return parts.join('\r\n')}
function calendar(events,label){const now=new Date().toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'');let text=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Changsha for Two//Trip Planner//ZH','CALSCALE:GREGORIAN','METHOD:PUBLISH','X-WR-CALNAME:'+icsEscape(label),'X-WR-TIMEZONE:Asia/Shanghai'];for(const e of events){let key=[e.date,e.time,e.title,e.person].join('|');let h=2166136261;for(let i=0;i<key.length;i++){h^=key.charCodeAt(i);h=Math.imul(h,16777619)}text.push('BEGIN:VEVENT','UID:'+(h>>>0).toString(16)+'@changsha-for-two','DTSTAMP:'+now,'DTSTART:'+utcStamp(e.date,e.time),'DTEND:'+utcStamp(e.date,e.end),'SUMMARY:'+icsEscape(e.title),'LOCATION:'+icsEscape(e.place),'DESCRIPTION:'+icsEscape(e.body+'\n时间为北京时间；计划未代为预约。'),'BEGIN:VALARM','ACTION:DISPLAY','TRIGGER:-PT'+(e.alarm||30)+'M','DESCRIPTION:'+icsEscape(e.title),'END:VALARM','END:VEVENT')}text.push('END:VCALENDAR');const content=text.map(fold).join('\r\n')+'\r\n';const blob=new Blob([content],{type:'text/calendar;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='changsha-'+label.replace(/[^\w\u4e00-\u9fa5-]/g,'-')+'.ics';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000);toast('日历文件已生成，请在手机日历中导入并检查通知权限')}
function dayCalendar(d,i){return d.events.map((e,n)=>({date:d.date,time:e.time,end:e.end,title:'计划：'+e.title,place:e.place,body:e.body+'\n交通：'+e.transit+'\n'+e.extra,person:eventPerson(i,n),alarm:30}))}
function openCalendar(day=false){document.getElementById('calType').value=day?'day':'essential';document.getElementById('calendarDialog').showModal()}
document.getElementById('hotelLink').href=map(hotel);
document.getElementById('calendarTop').addEventListener('click',()=>openCalendar());
document.getElementById('closeDialog').addEventListener('click',()=>document.getElementById('calendarDialog').close());
document.getElementById('calendarDialog').addEventListener('click',e=>{if(e.target===e.currentTarget){let r=e.currentTarget.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.currentTarget.close()}});
document.getElementById('downloadCalendar').addEventListener('click',()=>{let type=document.getElementById('calType').value,person=document.getElementById('person').value;let events=type==='essential'?[...essential]:type==='day'?dayCalendar(days[state.day],state.day):[...essential,...days.flatMap(dayCalendar)];events=events.filter(e=>person==='all'||e.person===person||e.person==='both');calendar(events,`长沙-${person==='all'?'双人':person==='cai'?'蔡':'吴'}-${type==='day'?days[state.day].short:type==='full'?'完整日程':'出行提醒'}`);document.getElementById('calendarDialog').close()});
document.addEventListener('click',e=>{let b=e.target.closest('button');if(!b)return;if(b.dataset.view)changeView(b.dataset.view);else if(b.dataset.jump)changeView(b.dataset.jump);else if(b.dataset.day!==undefined){state.day=Number(b.dataset.day);render()}else if(b.dataset.area){state.area=b.dataset.area;render()}else if(b.hasAttribute('data-open-calendar'))openCalendar();else if(b.hasAttribute('data-calday'))openCalendar(true);else if(b.dataset.eventCal!==undefined){const n=Number(b.dataset.eventCal);calendar([dayCalendar(days[state.day],state.day)[n]],'长沙-'+days[state.day].short+'-'+days[state.day].events[n].title)}});
document.addEventListener('change',e=>{let t=e.target;if(t.dataset.done){local[t.dataset.done]=t.checked;save();t.closest('.event').classList.toggle('done',t.checked)}else if(t.dataset.book){local['book-'+t.dataset.book]=t.checked;save();render()}else if(t.dataset.bookNote){local['note-'+t.dataset.bookNote]=t.value;save()}});
render();
